openapi: 3.0.0
info:
  version: '0.1'
  title: 'Autoshowroom API'
  description: 'An API that allows clients to obtain existing information of orders, create, edit and delete orders'
  contact:
    name: Boris Kozhuhovskij
    email: borisgk98@ya.ru

servers:
  - url: http://localhost:8080/
    description: local server

paths:



  ### Auto
  /auto/{auto_id}:
    get:
      parameters:
        - name: auto_id
          in: path
          schema:
            type: integer
      description: Get information about auto by auto id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto'
        404:
          description: Not found auto by this auto_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auto'
      description: Change information about auto
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto'
    delete:
      parameters:
        - name: auto_id
          in: path
          schema:
            type: integer
      description: Delate information about auto by auto id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found auto by this auto_id
  /auto:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
      responses:
        200:
          description: List of autos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auto'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auto'
      description: Create information about auto
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto'
  ### AutoOption
  /autooption/{autooption_id}:
    get:
      parameters:
        - name: autooption_id
          in: path
          schema:
            type: integer
      description: Get information about autooption by autooption id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoOption'
        404:
          description: Not found autooption by this autooption_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoOption'
      description: Change information about autooption
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoOption'
    delete:
      parameters:
        - name: autooption_id
          in: path
          schema:
            type: integer
      description: Delate information about autooption by autooption id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found autooption by this autooption_id
  /autooption:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
      responses:
        200:
          description: List of autooptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutoOption'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoOption'
      description: Create information about autooption
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoOption'
  ### Order
  /order/{order_id}:
    get:
      parameters:
        - name: order_id
          in: path
          schema:
            type: integer
      description: Get information about order by order id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Not found order by this order_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      description: Change information about order
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    delete:
      parameters:
        - name: order_id
          in: path
          schema:
            type: integer
      description: Delate information about order by order id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found order by this order_id
  /order:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
        - name: status
          in: query
          required: false
          schema:
            type: string
          description: OrderStatus
      responses:
        200:
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      description: Create information about order
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  ### Customer
  /customer/{customer_id}:
    get:
      parameters:
        - name: customer_id
          in: path
          schema:
            type: integer
      description: Get information about customer by customer id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          description: Not found customer by this customer_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      description: Change information about customer
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    delete:
      parameters:
        - name: customer_id
          in: path
          schema:
            type: integer
      description: Delate information about customer by customer id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found customer by this customer_id
  /customer:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      description: Create information about customer
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  ### AutoModel
  /automodel/{automodel_id}:
    get:
      parameters:
        - name: automodel_id
          in: path
          schema:
            type: integer
      description: Get information about automodel by automodel id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoModel'
        404:
          description: Not found automodel by this automodel_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoModel'
      description: Change information about automodel
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoModel'
    delete:
      parameters:
        - name: automodel_id
          in: path
          schema:
            type: integer
      description: Delate information about automodel by automodel id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found automodel by this automodel_id
  /automodel:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
      responses:
        200:
          description: List of automodels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutoModel'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoModel'
      description: Create information about automodel
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoModel'
  ### Seller
  /seller/{seller_id}:
    get:
      parameters:
        - name: seller_id
          in: path
          schema:
            type: integer
      description: Get information about seller by seller id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Seller'
        404:
          description: Not found seller by this seller_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seller'
      description: Change information about seller
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Seller'
    delete:
      parameters:
        - name: seller_id
          in: path
          schema:
            type: integer
      description: Delate information about seller by seller id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found seller by this seller_id
  /seller:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
      responses:
        200:
          description: List of sellers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seller'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seller'
      description: Create information about seller
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Seller'
  ### AutoMark
  /automark/{automark_id}:
    get:
      parameters:
        - name: automark_id
          in: path
          schema:
            type: integer
      description: Get information about automark by automark id
      responses:
        200:
          description: Successful getting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoMark'
        404:
          description: Not found automark by this automark_id
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoMark'
      description: Change information about automark
      responses:
        200:
          description: Successful changing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoMark'
    delete:
      parameters:
        - name: automark_id
          in: path
          schema:
            type: integer
      description: Delate information about automark by automark id
      responses:
        200:
          description: Successful deletting
        404:
          description: Not found automark by this automark_id
  /automark:
    get:
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit for number of returnig values
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Offset for number of returnig values
      responses:
        200:
          description: List of automarks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AutoMark'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoMark'
      description: Create information about automark
      responses:
        200:
          description: Successful adding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoMark'


components:
  schemas:

    Auto:
      description: Contains information about automobiles
      properties:
        id:
          type: integer
        mark:
          type: object
          $ref: '#/components/schemas/AutoMark'
        model:
          type: object
          $ref: '#/components/schemas/AutoModel'
        options:
          type: array
          items:
            $ref: '#/components/schemas/AutoOption'

    AutoMark:
      description: Contains information about automobiles' marks
      properties:
        id:
          type: integer
        name:
          type: string
          example:
            audi

    AutoModel:
      description: Contains information about automobiles' models1
      properties:
        id:
          type: integer
        name:
          type: string
          example:
            q5

    AutoOption:
      description: Contains information about automobiles' options
      properties:
        id:
          type: integer
        name:
          type: string
          example:
            4x4

    Customer:
      description: Contains information about
      properties:
        id:
          type: integer
        name:
          type: string
          example:
            Boris
        surname:
          type: string
          example:
            Kozhuhovskij

    Order:
      description: Contains information about
      properties:
        id:
          type: integer
        seller:
          type: object
          $ref: '#/components/schemas/Seller'
        customer:
          type: object
          $ref: '#/components/schemas/Customer'
        auto:
          type: object
          $ref: '#/components/schemas/Auto'
        status:
          type: object
          $ref: '#/components/schemas/OrderStatus'

    OrderStatus:
      description: Contains information about
      enum:
        - ACCEPTED
        - IN_PROCESSING
        - DONE
      example:
        DONE

    Seller:
      description: Contains information about
      properties:
        id:
          type: integer
        name:
          type: string
          example:
            SallerName