
package com.mera.borisgk98.autoshowroom.server.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-23T23:49:38.786+03:00
 * Generated source version: 3.3.1
 *
 */
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-23T23:49:38.786+03:00", comments = "Apache CXF 3.3.1")
public final class AutoModelWebService_AutoModelServicePort_Client {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-23T23:49:38.786+03:00")
    private static final QName SERVICE_NAME = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "autoModelService");

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-23T23:49:38.786+03:00")
    private AutoModelWebService_AutoModelServicePort_Client() {
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-23T23:49:38.786+03:00")
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AutoModelService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AutoModelService ss = new AutoModelService(wsdlURL, SERVICE_NAME);
        AutoModelWebService port = ss.getAutoModelServicePort();


//        System.out.println("Invoking getRange...");
//        java.lang.Integer _getRange_arg0 = 1;
//        java.lang.Integer _getRange_arg1 = 2;
//        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.AutoModel> _getRange__return = port.getRange(_getRange_arg0, _getRange_arg1);
//        System.out.println("getRange.result=" + _getRange__return);
//
//        System.out.println("Invoking getAll...");
//        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.AutoModel> _getAll__return = port.getAll();
//        System.out.println("getAll.result=" + _getAll__return);

        System.out.println("Invoking read...");
        java.lang.Integer _read_arg0 = 20;
        com.mera.borisgk98.autoshowroom.server.soap.AutoModel _read__return = null;
        try {
            _read__return = port.read(_read_arg0);
            System.out.println("read.result=" + _read__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }

//        System.out.println("Invoking delete...");
//        java.lang.Integer _delete_arg0 = 10;
//        try {
//            port.delete(_delete_arg0);
//
//        } catch (ModelNotFound_Exception e) {
//            System.out.println("Expected exception: ModelNotFound has occurred.");
//            System.out.println(e.toString());
//        }
//
//        System.out.println("Invoking create...");
//        com.mera.borisgk98.autoshowroom.server.soap.AutoModel _create_arg0 = new AutoModel(){{ name = "LADA"; }};
//        com.mera.borisgk98.autoshowroom.server.soap.AutoModel _create__return = port.create(_create_arg0);
//        System.out.println("create.result=" + _create__return);


        System.out.println("Invoking update...");
        com.mera.borisgk98.autoshowroom.server.soap.AutoModel m = new AutoModel();
        m.name = "Lada";
        m.id = 2;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.AutoModel _update__return = port.update(m);
            System.out.println("update.result=" + _update__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }

        System.exit(0);
    }

}
