master:
  componentName: jenkins-master
  image: "jenkins/jenkins"

  overwriteConfig: true

  adminUser: admin

  installPlugins:
    - kubernetes:1.14.3
    - workflow-aggregator:2.6
    - workflow-job:2.31
    - credentials-binding:1.17
    - git:3.9.3
    - greenballs:1.15
    - google-login:1.4
    - role-strategy:2.9.0
    - locale:1.4

agent:
  enabled: true
  image: "jenkins/jnlp-slave"

  #autoadjust agent resources limits
  resources:
    requests:
      cpu: 200m
      memory: 1Gb
    limits:
      cpu: 200m
      memory: 1Gb

#to allow jenkins create slave pods
#rbac:
#  install: true