apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: autoshowroom-d
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: autoshowroom
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: autoshowroom
        image: gcr.io/rich-sprite-242414/autoshowroom-server:0.0.${BUILD_ID}
        ports:
        - containerPort: 8080
        - containerPort: 6565
        env:
        - name: spring.datasource.url
          value: jdbc:sqlserver://mssql-clusterip
        - name: spring.datasource.username
          value: sa
        - name: spring.kafka.bootstrap-servers
          value: kafka:9092
        - name: management.endpoints.web.exposure.include
          value: prometheus
        - name: spring.datasource.password        
          valueFrom:
            secretKeyRef:
              name: mssql
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: autoshowroom-lb
  labels:
    app: autoshowroom
spec:
  selector:
    app: autoshowroom
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 6565
      targetPort: 6565
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: autoshowroom-cip
  labels:
    app: autoshowroom
    monitoring: autoshowroom-monitor
spec:
  selector:
    app: autoshowroom
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 6565
      targetPort: 6565
  type: ClusterIP