apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoshowroom-d2-monitor
spec:
  #jobLabel: autoshowroom-java-server
  selector:
    matchLabels:
      app: autoshowroom
  endpoints:
  - path: /actuator/prometheus
    interval: 5s