
package com.mera.borisgk98.autoshowroom.server.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-06-03T11:44:07.707+03:00
 * Generated source version: 3.3.1
 *
 */
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.707+03:00", comments = "Apache CXF 3.3.1")
public final class AutoMarkWebService_AutomarkServicePort_Client {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.707+03:00")
    private static final QName SERVICE_NAME = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "automarkService");

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.707+03:00")
    private AutoMarkWebService_AutomarkServicePort_Client() {
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.707+03:00")
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AutomarkService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AutomarkService ss = new AutomarkService(wsdlURL, SERVICE_NAME);
        AutoMarkWebService port = ss.getAutomarkServicePort();

        {
        System.out.println("Invoking getAllAutoMark...");
        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.AutoMark> _getAllAutoMark__return = port.getAllAutoMark();
        System.out.println("getAllAutoMark.result=" + _getAllAutoMark__return);


        }
        {
        System.out.println("Invoking getRangeAutoMark...");
        java.lang.Integer _getRangeAutoMark_arg0 = null;
        java.lang.Integer _getRangeAutoMark_arg1 = null;
        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.AutoMark> _getRangeAutoMark__return = port.getRangeAutoMark(_getRangeAutoMark_arg0, _getRangeAutoMark_arg1);
        System.out.println("getRangeAutoMark.result=" + _getRangeAutoMark__return);


        }
        {
        System.out.println("Invoking createAutoMark...");
        com.mera.borisgk98.autoshowroom.server.soap.AutoMark _createAutoMark_arg0 = null;
        com.mera.borisgk98.autoshowroom.server.soap.AutoMark _createAutoMark__return = port.createAutoMark(_createAutoMark_arg0);
        System.out.println("createAutoMark.result=" + _createAutoMark__return);


        }
        {
        System.out.println("Invoking updateAutoMark...");
        com.mera.borisgk98.autoshowroom.server.soap.AutoMark _updateAutoMark_arg0 = null;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.AutoMark _updateAutoMark__return = port.updateAutoMark(_updateAutoMark_arg0);
            System.out.println("updateAutoMark.result=" + _updateAutoMark__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readAutoMark...");
        java.lang.Integer _readAutoMark_arg0 = null;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.AutoMark _readAutoMark__return = port.readAutoMark(_readAutoMark_arg0);
            System.out.println("readAutoMark.result=" + _readAutoMark__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteAutoMark...");
        java.lang.Integer _deleteAutoMark_arg0 = null;
        try {
            port.deleteAutoMark(_deleteAutoMark_arg0);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
