package com.mera.borisgk98.autoshowroom.server.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-27T14:33:34.108+03:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "autoService",
                  wsdlLocation = "http://localhost:8080/services/auto?wsdl",
                  targetNamespace = "http://soap.server.autoshowroom.borisgk98.mera.com/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00", comments = "Apache CXF 3.3.1")
public class AutoService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public final static QName SERVICE = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "autoService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public final static QName AutoServicePort = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "autoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/auto?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/auto?wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public AutoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public AutoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public AutoService() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns AutoWebService
     */
    @WebEndpoint(name = "autoServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public AutoWebService getAutoServicePort() {
        return super.getPort(AutoServicePort, AutoWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoWebService
     */
    @WebEndpoint(name = "autoServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.108+03:00")
    public AutoWebService getAutoServicePort(WebServiceFeature... features) {
        return super.getPort(AutoServicePort, AutoWebService.class, features);
    }

}
