
package com.mera.borisgk98.autoshowroom.server.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-06-03T11:44:06.974+03:00
 * Generated source version: 3.3.1
 *
 */
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:06.974+03:00", comments = "Apache CXF 3.3.1")
public final class CustomerWebService_CustomerServicePort_Client {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:06.974+03:00")
    private static final QName SERVICE_NAME = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "customerService");

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:06.974+03:00")
    private CustomerWebService_CustomerServicePort_Client() {
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:06.974+03:00")
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CustomerService ss = new CustomerService(wsdlURL, SERVICE_NAME);
        CustomerWebService port = ss.getCustomerServicePort();

        {
        System.out.println("Invoking createCustomer...");
        com.mera.borisgk98.autoshowroom.server.soap.Customer _createCustomer_arg0 = null;
        com.mera.borisgk98.autoshowroom.server.soap.Customer _createCustomer__return = port.createCustomer(_createCustomer_arg0);
        System.out.println("createCustomer.result=" + _createCustomer__return);


        }
        {
        System.out.println("Invoking readCustomer...");
        java.lang.Integer _readCustomer_arg0 = null;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.Customer _readCustomer__return = port.readCustomer(_readCustomer_arg0);
            System.out.println("readCustomer.result=" + _readCustomer__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRangeCustomer...");
        java.lang.Integer _getRangeCustomer_arg0 = null;
        java.lang.Integer _getRangeCustomer_arg1 = null;
        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.Customer> _getRangeCustomer__return = port.getRangeCustomer(_getRangeCustomer_arg0, _getRangeCustomer_arg1);
        System.out.println("getRangeCustomer.result=" + _getRangeCustomer__return);


        }
        {
        System.out.println("Invoking getAllCustomer...");
        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.Customer> _getAllCustomer__return = port.getAllCustomer();
        System.out.println("getAllCustomer.result=" + _getAllCustomer__return);


        }
        {
        System.out.println("Invoking updateCustomer...");
        com.mera.borisgk98.autoshowroom.server.soap.Customer _updateCustomer_arg0 = null;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.Customer _updateCustomer__return = port.updateCustomer(_updateCustomer_arg0);
            System.out.println("updateCustomer.result=" + _updateCustomer__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteCustomer...");
        java.lang.Integer _deleteCustomer_arg0 = null;
        try {
            port.deleteCustomer(_deleteCustomer_arg0);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
