package com.mera.borisgk98.autoshowroom.server.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-06-03T11:44:07.494+03:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "sellerService",
                  wsdlLocation = "http://35.228.60.112/services/seller?wsdl",
                  targetNamespace = "http://soap.server.autoshowroom.borisgk98.mera.com/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00", comments = "Apache CXF 3.3.1")
public class SellerService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public final static QName SERVICE = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "sellerService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public final static QName SellerServicePort = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "sellerServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://35.228.60.112/services/seller?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SellerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://35.228.60.112/services/seller?wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public SellerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public SellerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public SellerService() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns SellerWebService
     */
    @WebEndpoint(name = "sellerServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public SellerWebService getSellerServicePort() {
        return super.getPort(SellerServicePort, SellerWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerWebService
     */
    @WebEndpoint(name = "sellerServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T11:44:07.494+03:00")
    public SellerWebService getSellerServicePort(WebServiceFeature... features) {
        return super.getPort(SellerServicePort, SellerWebService.class, features);
    }

}
