
package com.mera.borisgk98.autoshowroom.server.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-27T14:33:34.706+03:00
 * Generated source version: 3.3.1
 *
 */
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.706+03:00", comments = "Apache CXF 3.3.1")
public final class OrderWebService_OrderServicePort_Client {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.706+03:00")
    private static final QName SERVICE_NAME = new QName("http://soap.server.autoshowroom.borisgk98.mera.com/", "orderService");

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.706+03:00")
    private OrderWebService_OrderServicePort_Client() {
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-05-27T14:33:34.706+03:00")
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OrderService ss = new OrderService(wsdlURL, SERVICE_NAME);
        OrderWebService port = ss.getOrderServicePort();

        {
        System.out.println("Invoking getAllOrder...");
        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.Order> _getAllOrder__return = port.getAllOrder();
        System.out.println("getAllOrder.result=" + _getAllOrder__return);


        }
        {
        System.out.println("Invoking readOrder...");
        java.lang.Integer _readOrder_arg0 = null;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.Order _readOrder__return = port.readOrder(_readOrder_arg0);
            System.out.println("readOrder.result=" + _readOrder__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createOrder...");
        com.mera.borisgk98.autoshowroom.server.soap.Order _createOrder_arg0 = null;
        com.mera.borisgk98.autoshowroom.server.soap.Order _createOrder__return = port.createOrder(_createOrder_arg0);
        System.out.println("createOrder.result=" + _createOrder__return);


        }
        {
        System.out.println("Invoking deleteOrder...");
        java.lang.Integer _deleteOrder_arg0 = null;
        try {
            port.deleteOrder(_deleteOrder_arg0);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRangeOrder...");
        java.lang.Integer _getRangeOrder_arg0 = null;
        java.lang.Integer _getRangeOrder_arg1 = null;
        java.util.List<com.mera.borisgk98.autoshowroom.server.soap.Order> _getRangeOrder__return = port.getRangeOrder(_getRangeOrder_arg0, _getRangeOrder_arg1);
        System.out.println("getRangeOrder.result=" + _getRangeOrder__return);


        }
        {
        System.out.println("Invoking updateOrder...");
        com.mera.borisgk98.autoshowroom.server.soap.Order _updateOrder_arg0 = null;
        try {
            com.mera.borisgk98.autoshowroom.server.soap.Order _updateOrder__return = port.updateOrder(_updateOrder_arg0);
            System.out.println("updateOrder.result=" + _updateOrder__return);

        } catch (ModelNotFound_Exception e) {
            System.out.println("Expected exception: ModelNotFound has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
