{
 "title": "Requests statistic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rest Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rest_seconds_count{application=\"java-service\"}"
    }
   ]
  },
  {
   "title": "Soap requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "soap_seconds_count{application=\"java-service\"}"
    }
   ]
  },
  {
   "title": "Kafka Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_request_seconds_count{application=\"java-service\"}"
    }
   ]
  },
  {
   "title": "gRPC Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grpc_requests_seconds_count{application=\"java-service\"}"
    }
   ]
  }
 ]
}